### ISSUE TITLE
在windows系统上因java代理路径错误导致无法启动项目

### ISSUE THREAD

**Issue by SeniorHan** [newhoo/mysql-explain#1]
MysqlPreRunCheck:79 
此处应做操作系统判断，如果是mac和Linux维持原实现，如果是windows，path需要多删一个/

**Comment by newhoo** [comment]
> MysqlPreRunCheck:79
> 此处应做操作系统判断，如果是mac和Linux维持原实现，如果是windows，path需要多删一个/

感谢，已经修复，平时主要用Mac
