### ISSUE TITLE
很不错的插件，支持作者。有个建议

### ISSUE THREAD

**Issue by meiMingle** [newhoo/mysql-explain#3]
建议将默认的 Explain 执行前过滤条件改为 insert,INSERT,update,UPDATE,delete,DELETE
要不项目一启动就报错  ：You have an error in your SQL syntax。。。。。。，用户体验不太好

![image](https://user-images.githubusercontent.com/39942874/106735469-3f934e00-664f-11eb-9427-1df7f6db2021.png)
![image](https://user-images.githubusercontent.com/39942874/106736744-cf85c780-6650-11eb-9f0b-adcb41f7729d.png)

**Comment by meiMingle** [comment]
建议执行前过滤支持正则匹配或者添加一个‘忽略大小写’选项

**Comment by newhoo** [comment]
你用的是mysql版本是5.6以下吗？好像5.6以下不支持DML的EXPLAIN。这个默认值可以这样设置：打开idea，关闭所有项目，然后找到设置，在里头设置【Explain执行前过滤条件】，应用后就会应用到所有新打开的项目。

**Comment by newhoo** [comment]
每个项目单独设置一下也可以的，基本不费什么时间。我只是把自己觉得还算好用的插件分享给大家用，不一定能考虑到各种情况哈，用户体验难免欠缺，感谢你的使用和反馈！
